### ISSUE TITLE
Reset Password Action Throws First and Last Name Validation Errors

### ISSUE THREAD

**Issue by allthesignals** [MAPC/massbuilds#159] opened 2016-12-21 17:37 UTC
Attempting to reset a password throws and first and last name validation error. It is attempting to validate the first and last name password fields, but should not do that. The path for this is to remove the first and last name validations from the User model.

**Comment by mzagaja** [comment] 2016-12-27 15:28
This should have been fixed in 588a937d8880dc170c5ab7bb3c67bfe7f0032109 but due to the validation should be moot for new users going forward. I'm going to attempt to reproduce this bug locally to debug this but am not sure why this is failing. My hypothesis is that new_record? is returning true when we do a password reset because it is instantiating a new instance of the user and then saving it over the old one. It does not actually check to see if a user existed before (see https://github.com/rails/rails/blob/5d1402a1011f58b405e42007d3ceed4e122d273e/activerecord/lib/active_record/persistence.rb#L85).

**Closed** 2016-12-27 20:58 UTC
Labels: bug
