### ISSUE TITLE
Error logging out of site

### ISSUE THREAD

**Issue by sannphilbrick** [MAPC/massbuilds#220] opened 2017-05-17 17:55 UTC
When trying to sign out of my massbuilds account (www.massbuilds.com/users/sign_out) I am given the message: "The change you wanted was rejected. Maybe you tried to change something you didn't have access to. If you are the application owner check the logs for more information."

This was using a chrome browser

**Comment by mzagaja** [comment] 2017-06-22 16:50
I think this is a duplicate of #178

**Closed by mzagaja** 2017-06-22 16:50 UTC
Labels: bug
